theme: jekyll-theme-minimal

# Configuración general del sitio:
title: null
# logo: # filename of a logo image that has been placed into your images directory
# email: mmilicich at dc.uba.ar

# Para que no muestre la leyenda de "View my GitHub profile":
github:
  is_project_page: false
