theme: jekyll-theme-minimal

# Configuración general del sitio:
title: Mariana Milicich
# logo: # filename of a logo image that has been placed into your images directory

email: mmilicich at dc.uba.ar
